### ISSUE TITLE
Treffen No. 1

### ISSUE THREAD

**Issue by yyazgan** [ProPra16/programmierpraktikum-abschlussprojekt-ji#1]
Hallo liebe Gruppe,

ich betreue euch. Bitte kommt doch in meine Übung am Freitag um 16:30 Uhr. 

Viele Grüße 

Yasin

**Comment by jsticker92** [comment]
Zitat von yyazgan <notifications@github.com>:

> Hallo liebe Gruppe,
>
> ich betreue euch. Bitte kommt doch in meine Übung am Freitag um 16:30 Uhr.
>
>
> Viele Grüße
>
> Yasin
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-ji/issues/1



Alles klar danke machen wir!
Bis dann MfG
die Gruppe
