### ISSUE TITLE
Probleme beim Einbinden der Bibliothek

### ISSUE THREAD

**Issue by yyazgan** [ProPra16/programmierpraktikum-abschlussprojekt-ji#2]

**Comment by IvanVilimonovic** [comment]
Die Bibliothek ist eingebunden. Wie können wir jetzt den Code, den wir in Form von Strings haben mit Hilfe der Bib. kompilieren?

**Comment by yyazgan** [comment]
Es ist eigentlich sehr klar dokumentiert: http://kata.bendisposto.de/vk/core/api/CompilationUnit.html#CompilationUnit-java.lang.String-java.lang.String-boolean-

Der erste Parameter ist der Klassenname und der zweite der komplette Quelltext der Klasse.
