### ISSUE TITLE
Treffen

### ISSUE THREAD

**Issue by IvanVilimonovic** [ProPra16/programmierpraktikum-abschlussprojekt-ji#4]
Hallo Yasin,

könnten wir uns noch einmal vor der Abgabe treffen?

Viele Grüße,

ji-Team

**Comment by yyazgan** [comment]
Das mit dem Treffen ist leider zu kurzfristig. Ich hatte für den Mittwoch nach einem Raum angefragt, aber es scheint keiner frei zu sein. Das Blöde ist, dass unsere Übung nach der Abgabe ist. Gebt euer bestes bis morgen und ansonsten frage ich mal nach, ob man noch zusätzliche Zeit um nachbessern bekommen könnte.

**Comment by yyazgan** [comment]
Ihr könnt bis zum kommenden Samstag nachbessern, falls Bedarf besteht. Wir können uns auch am Freitag treffen, falls ihr möchtet.

**Comment by IvanVilimonovic** [comment]
Ja bitte. ich würde mich schon vorher gerne treffen, falls Sie Zeit haben, weil am Freitag der letzte Tag vor der Abgabe ist und ich am Samstag noch eine Klausur schreibe. 

 

Viele Grüße,

 

Ivan

 

Von: yyazgan [mailto:notifications@github.com] 
Gesendet: Samstag, 16. Juli 2016 19:43
An: ProPra16/programmierpraktikum-abschlussprojekt-ji <programmierpraktikum-abschlussprojekt-ji@noreply.github.com>
Cc: IvanVilimonovic <ivan.vilimonovic@uni-duesseldorf.de>; Author <author@noreply.github.com>
Betreff: Re: [ProPra16/programmierpraktikum-abschlussprojekt-ji] Treffen (#4)

 

Ihr könnt bis zum kommenden Samstag nachbessern, falls Bedarf besteht. Wir können uns auch am Freitag treffen, falls ihr möchtet.

**Comment by IvanVilimonovic** [comment]
Hey, du hast nicht mehr geantwortet, daher wollte ich fragen, ob wir uns heute treffen, oder nicht und um wie viel Uhr? Ist es so wie beim letzten mal um 16:30? Dann würde gerne vorbeikommen.

Gruß,

Ivan

**Comment by yyazgan** [comment]
Ja, kommt heute um 16:30 Uhr in den Raum von letztem Mal (Übungsraum).
